### ISSUE TITLE
please trim commits text

### ISSUE THREAD

**Issue by gordielachance** [sudar/wp-github-commits#2]
Hi !
Could you trim the text from the commits so they don't exceed a length ?
I got commits displayed that have a title which is more than 900 characters long...

**Comment by gordielachance** [comment]
I fixed it with this : 

        // TODO: Make it plugable
        $output = '<ul class = "github-commits">';
        foreach($commits as $commit) {
            $counter ++;
            $commit_message = wp_trim_words( $commit->commit->message, 30, '...' );
            $output .= '<li class = "github-commit">';
            $output .= "<a href = 'https://github.com/$user/$repo/commit/{$commit->sha}'>" . $commit_message . '</a> ';

**Comment by sudar** [comment]
@gordielachance 

Thanks for brining this to my attention. Will fix it right away.

**Comment by sudar** [comment]
This was fixed in https://github.com/sudar/wp-github-commits/commit/295bfab0ae8b12edcc987177502e8f1a51473fc3 and v0.6 of the plugin has been released with the fix.

**Comment by gordielachance** [comment]
Thanks !
